#!/usr/bin/env bash
set -e

# ==========================================
# GITHUB BOARD LIVE SYNC (2026 Enterprise)
# ==========================================
# Syncs open GitHub Issues to a local Markdown dashboard file.
# Usage: ./sync-github-board.sh [output_file.md]

if ! command -v gh &> /dev/null; then
  echo "Error: GitHub CLI (gh) not found."
  exit 1
fi

if ! gh auth status &> /dev/null; then
  echo "Error: Not authenticated with GitHub CLI."
  exit 1
fi

OUTPUT_FILE="${1:-.opencode/github-board.md}"

# Create directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

echo "Syncing GitHub Issues to $OUTPUT_FILE..."

cat << 'MARKDOWN_EOF' > "$OUTPUT_FILE"
# 👑 CEO Dashboard - Live GitHub Issues
*Generated by `sync-github-board.sh`*
---

## 🟢 Open Issues (To-Do & In Progress)
MARKDOWN_EOF

# Fetch open issues
gh issue list --state open --json number,title,labels,url --limit 50 --jq '
  .[] | "- [ ] [#" + (.number | tostring) + " " + .title + "](" + .url + ") " +
  (if .labels | length > 0 then "**(" + (.labels | map(.name) | join(", ")) + ")**" else "" end)
' >> "$OUTPUT_FILE"

cat << 'MARKDOWN_EOF' >> "$OUTPUT_FILE"

---
## 🔴 Recently Closed
MARKDOWN_EOF

# Fetch recently closed issues (last 10)
gh issue list --state closed --json number,title,labels,url --limit 10 --jq '
  .[] | "- [x] ~[#" + (.number | tostring) + " " + .title + "](" + .url + ")~"
' >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "Last synced: $(date)" >> "$OUTPUT_FILE"

echo "✅ [CEO Dashboard Sync] Board updated in $OUTPUT_FILE"
